--drop table list
DROP TABLE CODE;
DROP TABLE USERS;
DROP TABLE PREFERENCES;
DROP TABLE CALENDAR;
DROP TABLE HISTORY;
DROP TABLE POSITION;

--create new tables
CREATE TABLE CODE(
	BCOD CHAR(5),
	BUY_DATE DATE NOT NULL,
	PRIMARY KEY(BCOD)
);

CREATE TABLE USERS(
	MAIL CHAR(30),
	PASSWORD CHAR(20) NOT NULL,
	BCOD CHAR(5) NOT NULL,
	NAME CHAR(15) NOT NULL,
	SURNAME CHAR(15) NOT NULL,
	PRIMARY KEY(MAIL),
	CONSTRAINT chk_Pass CHECK(LENGTH(PASSWORD)>=8),
	FOREIGN KEY(BCOD) REFERENCES CODE(BCOD)
);

CREATE TABLE PREFERENCES(
	MAIL CHAR(30),
	PERIMETER INT NOT NULL,
	COLOUR CHAR(10) NOT NULL,
	SONG CHAR(30) NOT NULL,
	DOCT CHAR(30) NULL,
	MESSAGE CHAR(40) NOT NULL,
	AUTO_CLEAN CHAR(1) NOT NULL,
	PRIMARY KEY(MAIL),
	FOREIGN KEY(MAIL) REFERENCES USERS(MAIL)
);

CREATE TABLE CALENDAR(
	MAIL CHAR(30),
	DATA DATE, 
	ORA CHAR(10),
	MESSAGE CHAR(40) NOT NULL,
	PRIMARY KEY(MAIL, DATA, ORA),
	FOREIGN KEY(MAIL) REFERENCES USERS(MAIL)
);

CREATE TABLE HISTORY(
	MAIL CHAR(30),
	DATA DATE, 
	ORA CHAR(10),
	MESSAGE CHAR(100) NOT NULL,
	PRIMARY KEY(MAIL, DATA, ORA),
	FOREIGN KEY(MAIL) REFERENCES USERS(MAIL)
);

CREATE TABLE POSITION(
	MAIL CHAR(30),
	LATITUDE INT,
	LONGITUDE INT,
	ORA CHAR(10),
	PRIMARY KEY(MAIL, LATITUDE, LONGITUDE, ORA)
	FOREIGN KEY(MAIL) REFERENCES USERS(MAIL)
); 
