--drop table list
DROP TABLE CODE;
DROP TABLE USERS;
DROP TABLE PREFERENCES;
DROP TABLE CALENDAR;
DROP TABLE HISTORY;
DROP TABLE POSITION;

--create new tables
CREATE TABLE CODE(
	BCOD CHAR(5),
	BUY_DATE DATE NOT NULL,
	PRIMARY KEY(BCOD)
);

CREATE TABLE USERS(
	MAIL CHAR(30),
	PASSWORD CHAR(20) NOT NULL,
	BCOD CHAR(5) NOT NULL,
	NAME CHAR(15) NOT NULL,
	SURNAME CHAR(15) NOT NULL,
	PRIMARY KEY(MAIL),
	CONSTRAINT chk_Pass CHECK(LENGTH(PASSWORD)>=8),
	FOREIGN KEY(BCOD) REFERENCES CODE(BCOD)
);

CREATE TABLE PREFERENCES(
	MAIL CHAR(30),
	PERIMETER INT NOT NULL,
	COLOUR CHAR(10) NOT NULL,
	SONG CHAR(30) NOT NULL,
	DOCT CHAR(30) NULL,
	MESSAGE CHAR(40) NOT NULL,
	AUTO_CLEAN CHAR(1) NOT NULL,
	PRIMARY KEY(MAIL),
	FOREIGN KEY(MAIL) REFERENCES USERS(MAIL)
);

CREATE TABLE CALENDAR(
	MAIL CHAR(30),
	CODE INT AUTO_INCREMENT,
	DESCRIPTION CHAR(100) NOT NULL,
	DONE CHAR(1) NOT NULL,
	TITLE CHAR(10),
	DATA DATE, 
	ORA CHAR(10),
	MESSAGE CHAR(40) NOT NULL,
	PRIORITY CHAR(1) NOT NULL,
	REPEAT CHAR(1) NOT NULL,
	PRIMARY KEY(MAIL, CODE),
	FOREIGN KEY(MAIL) REFERENCES USERS(MAIL)
);

CREATE TABLE HISTORY(
	MAIL CHAR(30),
	CODE INT AUTO_INCREMENT,
	READ CHAR(1) NOT NULL,
	DATA DATE, 
	ORA CHAR(10),
	MESSAGE CHAR(100) NOT NULL,
	PRIMARY KEY(MAIL, CODE),
	FOREIGN KEY(MAIL) REFERENCES USERS(MAIL)
);
