--drop table list
DROP TABLE CODE;
DROP TABLE USERS;
DROP TABLE DEVICE;
DROP TABLE PREFERENCES;
DROP TABLE CALENDAR;
DROP TABLE HISTORY;

--create new tables
CREATE TABLE CODE(
	BCOD CHAR(5),
	BUY_DATE DATE NOT NULL,
	PRIMARY KEY(BCOD)
);

CREATE TABLE USERS(
	EMAIL CHAR(30),
	PASSWORD CHAR(20) NOT NULL,
	BCOD CHAR(5) UNIQUE NOT NULL,
	NAME CHAR(15) NOT NULL,
	SURNAME CHAR(15) NOT NULL,
	PRIMARY KEY(EMAIL),
	CONSTRAINT chk_Pass CHECK(LENGTH(PASSWORD)>=8),
	FOREIGN KEY(BCOD) REFERENCES CODE(BCOD)
);

CREATE TABLE DEVICE(
  EMAIL CHAR(30),
	DEVICEID CHAR(140),
	ANORAPP CHAR(10) NOT NULL,
	PRIMARY KEY(EMAIL, DEVICEID),
	FOREIGN KEY(EMAIL) REFERENCES USERS(EMAIL)
);

CREATE TABLE PREFERENCES(
	EMAIL CHAR(30),
	PERIMETER INTEGER NOT NULL,
	COLOUR CHAR(10) NOT NULL,
	SONG CHAR(30) NOT NULL,
	DOCT CHAR(30) NULL,
	MESSAGE CHAR(40) NOT NULL,
	AUTO_CLEAN CHAR(1) NOT NULL,
	DOC_ACCESS CHAR(1) NOT NULL,
	ADDRESS CHAR(50) NOT NULL,
	PRIMARY KEY(EMAIL),
	FOREIGN KEY(EMAIL) REFERENCES USERS(EMAIL)
);

CREATE TABLE CALENDAR(
	EMAIL CHAR(30),
	CODE CHAR(24),
	DESCRIPTION CHAR(100) NOT NULL,
	DONE CHAR(1) NOT NULL,
	TITLE CHAR(10),
	DATA DATE, 
	ORA CHAR(10),
	MESSAGE CHAR(40) NOT NULL,
	PRIORITY CHAR(1) NOT NULL,
	PRIMARY KEY(EMAIL, CODE),
	FOREIGN KEY(EMAIL) REFERENCES USERS(EMAIL)
);

CREATE TABLE HISTORY(
	EMAIL CHAR(30),
	CODE CHAR (24),
	READ CHAR(1) NOT NULL,
	DATA DATE, 
	ORA CHAR(10),
	MESSAGE CHAR(100) NOT NULL,
	PRIMARY KEY(EMAIL, CODE),
	FOREIGN KEY(EMAIL) REFERENCES USERS(EMAIL)
);

CREATE TABLE POSITION(
	EMAIL CHAR(30),
	LATITUDE CHAR(20) NOT NULL,
	LONGITUDE CHAR(20) NOT NULL,
	PRIMARY KEY(EMAIL),
	FOREIGN KEY(EMAIL) REFERENCES USERS(EMAIL)
);
